CC=g++
CFLAGS=-std=c++11

all: unl2tsv allwise_p3as_tbl2tsv allsky_4band_p1bm_frm_tbl2tsv

unl2tsv: unl2tsv.cc
	$(CC) $(CFLAGS) -o $@ $<

allwise_p3as_tbl2tsv: allwise_p3as_tbl2tsv.cc
	$(CC) $(CFLAGS) -o $@ $<

allsky_4band_p1bm_frm_tbl2tsv: allsky_4band_p1bm_frm_tbl2tsv.cc
	$(CC) $(CFLAGS) -o $@ $<
